SAI_password: "Epharma2021"
SAI_user: "EPH -161215-NS9"
SAI_link: "https://ppsai-abasto.imss.gob.mx/abasto-web/reporteAltas"

PREI_password: 'EPH161215NS9'
PREI_user: '0000150462'
PREI_link: "https://pispdigital.imss.gob.mx/piref/"

PAQS_IMSS:
  PAQ_IMSS_2025:
    file_path: "C:\\Users\\arman\\Dropbox\\FACT 2025\\Copy of Generacion facturas IMSS 2024.xlsx"
    sheet: "Reporte Paq"
    rows:
      - Folio
      - Referencia
      - Alta

columns_IMSS_altas:
  - noAlta
  - fechaAltaTrunc
  - noContrato
  - noOrden
  - clave
  - cantRecibida
  - importe
  - fpp
  - clasPtalRecep
  - descUnidad
  - clasPtalDist
  - descDist
  - totalItems
  - resguardo

columns_IMSS_orders:
  - contrato
  - solicitud
  - orden
  - generacion
  - cveArticulo
  - fechaExpedicion
  - lugarEntrega
  - descripciónEntrega
  - direccionEntrega
  - destinoFinal
  - estatus
  - fechaEntrega
  - cantidadSolicitada
  - precio
  - importeSinIva

columns_PREI: 
  - Documento
  - Folio Fiscal
  - Fecha Factura
  - Importe
  - Fecha Carga
  - Unidad Negocio
  - Contra Recibo
  - Estado C.R.

facturas_path:
  - "C:\\Users\\arman\\Dropbox\\FACT 2023"
  - "C:\\Users\\arman\\Dropbox\\FACT 2024"
  - "C:\\Users\\arman\\Dropbox\\FACT 2025"
